language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
before_install:
  - pip install codecov
after_success:
  - codecov

install:
  - pip install -r requirements.txt

# command to run tests
script: nosetests
